
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author minha
 */
public class Add_Employee extends javax.swing.JFrame {
    MyHashTable hashTable;
    /**
     * Creates new form AddEmployee
     */
    public Add_Employee(MyHashTable hashTable) {
        this.hashTable = hashTable; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        AddEmployeeLabel = new javax.swing.JLabel();
        AddEmployeeConfirm = new javax.swing.JButton();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        SexLabel = new javax.swing.JLabel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumberField = new javax.swing.JTextField();
        EmployeeStatusLabel = new javax.swing.JLabel();
        PartTimeButton = new javax.swing.JRadioButton();
        FullTimeButton = new javax.swing.JRadioButton();
        DeductionRateLabel = new javax.swing.JLabel();
        DeductionRateField = new javax.swing.JTextField();
        HourlyWageLabel = new javax.swing.JLabel();
        HourlyWageField = new javax.swing.JTextField();
        HoursPerWeekLabel = new javax.swing.JLabel();
        HoursPerWeekField = new javax.swing.JTextField();
        WeeksPerYearLabel = new javax.swing.JLabel();
        WeeksPerYearField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        AddEmpBackButton = new javax.swing.JButton();
        LocationComboBox = new javax.swing.JComboBox();
        LocationLabel = new javax.swing.JLabel();
        ErrorMessage = new javax.swing.JLabel();
        SalaryLabel = new javax.swing.JLabel();
        SalaryField = new javax.swing.JTextField();
        SexBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddEmployeeLabel.setText("Add Employee");

        AddEmployeeConfirm.setText("Confirm");
        AddEmployeeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeConfirmActionPerformed(evt);
            }
        });

        FirstNameLabel.setText("First Name");

        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });

        LastNameLabel.setText("Last Name");

        SexLabel.setText("Sex");

        EmployeeNumberLabel.setText("Employee Number");

        EmployeeStatusLabel.setText("Employee Status");

        buttonGroup2.add(PartTimeButton);
        PartTimeButton.setText("Part-time");
        PartTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartTimeButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(FullTimeButton);
        FullTimeButton.setText("Full-time");
        FullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullTimeButtonActionPerformed(evt);
            }
        });

        DeductionRateLabel.setText("Deducation Rate");
        DeductionRateLabel.setVisible(false);

        DeductionRateField.setVisible(false);
        DeductionRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeductionRateFieldActionPerformed(evt);
            }
        });

        HourlyWageLabel.setText("Hourly Wage");
        HourlyWageLabel.setVisible(false);

        HourlyWageField.setVisible(false);

        HoursPerWeekLabel.setText("Hours Per Week");
        HoursPerWeekLabel.setVisible(false);

        HoursPerWeekField.setVisible(false);

        WeeksPerYearLabel.setText("Weeks Per Year");
        WeeksPerYearLabel.setVisible(false);

        WeeksPerYearField.setVisible(false);

        jLabel1.setText("Age");

        AddEmpBackButton.setText("Back");
        AddEmpBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpBackButtonActionPerformed(evt);
            }
        });

        LocationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mississauga", "Ottawa", "Chicago" }));
        LocationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationComboBoxActionPerformed(evt);
            }
        });

        LocationLabel.setText("Location");

        ErrorMessage.setText("Invalid Input!");
        ErrorMessage.setVisible(false);

        SalaryLabel.setVisible(false);
        SalaryLabel.setText("Salary");

        SalaryField.setVisible(false);
        SalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryFieldActionPerformed(evt);
            }
        });

        SexBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other"}));
        SexBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddEmployeeLabel)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(FirstNameField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SexLabel)
                                .addGap(27, 27, 27)
                                .addComponent(SexBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddEmployeeConfirm)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeNumberLabel)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmployeeNumberField)
                                    .addComponent(AgeField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                            .addComponent(AddEmpBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrorMessage)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(HoursPerWeekLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoursPerWeekField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HourlyWageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HourlyWageField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(EmployeeStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PartTimeButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(SalaryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(DeductionRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullTimeButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WeeksPerYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WeeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddEmployeeLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeNumberLabel)
                    .addComponent(EmployeeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexLabel)
                    .addComponent(SexBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeStatusLabel)
                    .addComponent(PartTimeButton)
                    .addComponent(FullTimeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeductionRateLabel)
                    .addComponent(DeductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationLabel)
                    .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryLabel)
                    .addComponent(SalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourlyWageLabel)
                    .addComponent(HourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoursPerWeekLabel)
                    .addComponent(HoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeeksPerYearLabel)
                    .addComponent(WeeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(AddEmployeeConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddEmpBackButton)
                .addGap(18, 18, 18)
                .addComponent(ErrorMessage)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void FullTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullTimeButtonActionPerformed
           DeductionRateLabel.setVisible(true);     // if FTE button is selected, make full time attributes visible, part time attributes invisible
            DeductionRateField.setVisible(true);
            DeductionRateField.setText("");
            SalaryLabel.setVisible(true);
            SalaryField.setVisible(true);
            SalaryField.setText("");
            HourlyWageLabel.setVisible(false);
            HourlyWageField.setVisible(false);
            HourlyWageField.setText("");
            HoursPerWeekLabel.setVisible(false);
            HoursPerWeekField.setVisible(false);
            HoursPerWeekField.setText("");
            WeeksPerYearLabel.setVisible(false);
            WeeksPerYearField.setVisible(false);
            WeeksPerYearField.setText("");
    }//GEN-LAST:event_FullTimeButtonActionPerformed

    private void PartTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartTimeButtonActionPerformed
       DeductionRateLabel.setVisible(true);     // if PTE button is selected, make part time attributes visible, full time invisible
            DeductionRateField.setVisible(true);
            DeductionRateField.setText("");
            HourlyWageLabel.setVisible(true);
            HourlyWageField.setVisible(true);
            HourlyWageField.setText("");
            HoursPerWeekLabel.setVisible(true);
            HoursPerWeekField.setVisible(true);
            HoursPerWeekField.setText("");
            WeeksPerYearLabel.setVisible(true);
            WeeksPerYearField.setVisible(true);
            WeeksPerYearField.setText("");
            SalaryLabel.setVisible(false);
            SalaryField.setVisible(false);
            SalaryField.setText("");

        
    }//GEN-LAST:event_PartTimeButtonActionPerformed

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldActionPerformed
   
    private void AddEmployeeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeConfirmActionPerformed
        // TODO add your handling code here:
        
        if (LastNameField.getText().equals("") || FirstNameField.getText().equals("") || SexBox.getItemCount() == 0){
       ErrorMessage.setVisible(true);
   }
   
   else if (PartTimeButton.isSelected() == true){                       //add PTE
         try{       
            Double.parseDouble(HoursPerWeekField.getText());            //get the text of the values in the textbox and convert it to int or double
            Integer.parseInt(AgeField.getText());
            Integer.parseInt(EmployeeNumberField.getText());
            Double.parseDouble(HourlyWageField.getText());
            Double.parseDouble(WeeksPerYearField.getText());
            Double.parseDouble(DeductionRateField.getText());
            
            int en = parseInt(EmployeeNumberField.getText());
            String firstN = FirstNameField.getText();
            String lastN = LastNameField.getText();
            int age = parseInt(AgeField.getText());
            int sex = SexBox.getSelectedIndex();
            int location = LocationComboBox.getSelectedIndex();
            double deduct = parseDouble(DeductionRateField.getText());
            double hourlyWage = parseDouble(HourlyWageField.getText());
            double hoursInWeek = parseDouble(HoursPerWeekField.getText());
            double weeksInYear = parseDouble(WeeksPerYearField.getText());
            PTE PartTimer = new PTE (en, firstN, lastN, age, sex, deduct, location, hourlyWage, hoursInWeek, weeksInYear);
            this.hashTable.addEmployee(PartTimer);
            System.out.println(this.hashTable.buckets.length);
            //System.out.println(this.hashTable.getRealSize());    
            Successfully_Added new_Window = new Successfully_Added();
            new_Window.setVisible(true);
            FirstNameField.setText("");             //reset the textboxes
            LastNameField.setText("");
            AgeField.setText("");
            EmployeeNumberField.setText("");
            PartTimeButton.setSelected(false);
            DeductionRateField.setText("");
            HourlyWageField.setText("");
            HoursPerWeekField.setText("");
            WeeksPerYearField.setText("");
}
         catch (Exception e){
                ErrorMessage.setVisible(true);
            }
   }
   else{                                            //add FTE, code below is the same as PTE
       try{
            Double.parseDouble(DeductionRateField.getText());
            Double.parseDouble(SalaryField.getText());
            Integer.parseInt(AgeField.getText());
            Integer.parseInt(EmployeeNumberField.getText());  
            
            int en = parseInt(EmployeeNumberField.getText());           
            String firstN = FirstNameField.getText();
            String lastN = LastNameField.getText();
            int age = parseInt(AgeField.getText());
            int sex = SexBox.getSelectedIndex();
            int location = LocationComboBox.getSelectedIndex();
            double deduct = parseDouble(DeductionRateField.getText());
            double salary = parseDouble(SalaryField.getText());
            FTE FullTimer = new FTE (en, firstN, lastN, age, sex, deduct, location, salary);
            this.hashTable.addEmployee(FullTimer);       
            //System.out.println(this.hashTable.getRealSize());
             Successfully_Added new_Window = new Successfully_Added();
            new_Window.setVisible(true);
            FirstNameField.setText("");
            LastNameField.setText("");
            AgeField.setText("");
            EmployeeNumberField.setText("");
            PartTimeButton.setSelected(false);
            DeductionRateField.setText("");
            SalaryField.setText("");
            }
                    
            catch (Exception e){
                ErrorMessage.setVisible(true);
            }
            }
       
       
    }//GEN-LAST:event_AddEmployeeConfirmActionPerformed

    private void AddEmpBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpBackButtonActionPerformed
/*MainJFrame new_Window = new MainJFrame();
new_Window.setVisible(true);
Add_Employee.this.setVisible(false);*/
        dispose();

    }//GEN-LAST:event_AddEmpBackButtonActionPerformed

    private void LocationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationComboBoxActionPerformed

    private void SalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryFieldActionPerformed

    private void DeductionRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeductionRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeductionRateFieldActionPerformed

    private void SexBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmpBackButton;
    private javax.swing.JButton AddEmployeeConfirm;
    private javax.swing.JLabel AddEmployeeLabel;
    private javax.swing.JTextField AgeField;
    private javax.swing.JTextField DeductionRateField;
    private javax.swing.JLabel DeductionRateLabel;
    private javax.swing.JTextField EmployeeNumberField;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JLabel EmployeeStatusLabel;
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JRadioButton FullTimeButton;
    private javax.swing.JTextField HourlyWageField;
    private javax.swing.JLabel HourlyWageLabel;
    private javax.swing.JTextField HoursPerWeekField;
    private javax.swing.JLabel HoursPerWeekLabel;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JComboBox LocationComboBox;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JRadioButton PartTimeButton;
    private javax.swing.JTextField SalaryField;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JComboBox SexBox;
    private javax.swing.JLabel SexLabel;
    private javax.swing.JTextField WeeksPerYearField;
    private javax.swing.JLabel WeeksPerYearLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
