
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.*;
import java.util.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author minha
 */
public class Save extends javax.swing.JFrame {
    MyHashTable hashTable;
    private String saveLocation = "C:\\Users\\minha\\Downloads\\EmployeeManagementSystem\\src";
    /**
     * Creates new form Save
     */
    public Save(MyHashTable myHashTable) {
        this.hashTable = hashTable;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        FileNameBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter file name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FileNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(CancelButton)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FileNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(SaveButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        BufferedWriter bw = null;
        PTE tempPTE = null;
        FTE tempFTE = null;
        String separator = "^";
        String data = "";
        try{
            File file = new File("C:/" + FileNameBox.getText() + ".txt");
            if(!file.exists()){
               file.createNewFile();
           }
            FileWriter fw = new FileWriter(file);
            bw = new BufferedWriter(fw);
            for (int i = 0; i < hashTable.buckets.length; i++){
                for(int j = 0; j < hashTable.buckets[i].size(); j++){
                    if(hashTable.buckets[i].get(j) instanceof PTE){
                        data = tempPTE.getEmployeeNumber() + separator + 
                              tempPTE.getFirstName() + separator + 
                              tempPTE.getLastName() + separator + 
                              tempPTE.getAge() + separator + 
                              tempPTE.getSex() + separator + 
                              tempPTE.getDeductionRate() + separator + 
                              tempPTE.getLocation() + separator + 
                              tempPTE.getHourlyWage() +  separator + 
                              tempPTE.getHoursInWeek() + separator + 
                              tempPTE.weekInYears() + "\n";
                   }
                    if(hashTable.buckets[i].get(j) instanceof FTE){
                       data = tempFTE.getEmployeeNumber() + separator + 
                              tempFTE.getFirstName() + separator + 
                              tempFTE.getLastName() + separator + 
                              tempFTE.getAge() + separator + 
                              tempFTE.getSex() + separator + 
                              tempFTE.getDeductionRate() + separator + 
                              tempFTE.getLocation() + separator + 
                              tempFTE.getAnnualSalary() + "\n";
                   }
                   bw.write(data);
                   System.out.println("Successfully written file");
               }
           }
           
           
        }
        catch(IOException ioe){
            ioe.printStackTrace();
        }
        finally{
            try{
                if(bw != null){
                    bw.close();
                }
            }
            catch(Exception ex){
                System.out.println("Error in closing the BufferedWriter"+ex);
            }
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField FileNameBox;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
