/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author minha
 */
public class TheList extends javax.swing.JFrame {
    MyHashTable hashTable;
    /**
     * Creates new form TheList
     */
    public TheList(MyHashTable hashTable) {
        this.hashTable = hashTable;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OKButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableViewAll = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        jTableViewAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Gender", "Work Location", "Age", "Deduction Rate"
            }
        ));
        jTableViewAll.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableViewAllAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTableViewAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(OKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(OKButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    private void jTableViewAllAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableViewAllAncestorAdded
        // TODO add your handling code here:
        int rowIndex = 0;
        for (int i = 0; i < hashTable.buckets.length; i++){
            System.out.println(hashTable.buckets.length);
            System.out.println(hashTable.buckets[i].size());
            for (int j = 0; j < hashTable.buckets[i].size(); j++){
                System.out.println(hashTable.buckets[i].size());
             
                
                jTableViewAll.getModel().setValueAt(Integer.toString(hashTable.buckets[i].get(j).getEmployeeNumber()), rowIndex, 0);
                jTableViewAll.getModel().setValueAt(hashTable.buckets[i].get(j).getFirstName(), rowIndex, 1);
                jTableViewAll.getModel().setValueAt(hashTable.buckets[i].get(j).getLastName(), rowIndex, 2);
                    if(hashTable.buckets[i].get(j).getSex() == 0){
                jTableViewAll.getModel().setValueAt("Male", rowIndex, 3);
                    }
                    if(hashTable.buckets[i].get(j).getSex() == 1){
                jTableViewAll.getModel().setValueAt("Female", rowIndex, 3);
                    }
                    if(hashTable.buckets[i].get(j).getSex() == 2){
                jTableViewAll.getModel().setValueAt("Other", rowIndex, 3);
                    }
                    if(hashTable.buckets[i].get(j).getLocation() == 0){
                jTableViewAll.getModel().setValueAt("Mississauga", rowIndex, 4);
                    }
                    if(hashTable.buckets[i].get(j).getLocation() == 1){
                jTableViewAll.getModel().setValueAt("Ottawa", rowIndex, 4);
                    }
                    if(hashTable.buckets[i].get(j).getLocation() == 2){
                jTableViewAll.getModel().setValueAt("Chicago", rowIndex, 4);
                    }
                jTableViewAll.getModel().setValueAt(Integer.toString(hashTable.buckets[i].get(j).getAge()), rowIndex, 5);
                jTableViewAll.getModel().setValueAt(Double.toString(hashTable.buckets[i].get(j).getDeductionRate()), rowIndex, 6);
                rowIndex++;
                }
            
            
        }
        
    }//GEN-LAST:event_jTableViewAllAncestorAdded

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableViewAll;
    // End of variables declaration//GEN-END:variables
}
